title: Alen Brebrić # your name (or website title) here
logo: "/images/Snimka zaslona 2021-06-24 072631.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Date Of Bith: 21.02.2001<br> 
  Age: 20 <br>
  Location: <a href="https://www.google.com/maps/place/Piljenice/@45.4231134,16.7446312,12z/data=!3m1!4b1!4m5!3m4!1s0x476704cbc864ab69:0x7c556e1f20dd479f!8m2!3d45.4352675!4d16.8531562">Piljenice, Croatia</a> 
  <br>
  <b>Programing Skills:</b>
  <br>
  -C#
  <br>
  -C++
  <br>
  -HTML
  <br>
  <b>Database:</b>
  <br>
  -Fiebase
  <br>
  <b>Game Engines:</b>
  <br>
  -Unity
  <br>
  <b>3D modeling and aimations:</b>
  <br>
  -Blender
  <br>
  -Sweet Home 3D
  <br>
  -Fuze
  <br>
  -MakeHuman
  <br>
  -Mixamo
  <br>
  -ProgeCAD
  <br>
  <b>Other</b><br>
  -Github
  <br>
  -AutoCAD
  <br>
  <a href="https://emperorscorpion.itch.io/">View My ItchIo Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
