title: Alen Brebrić # your name (or website title) here
logo: "/images/Flag_of_the_Federal_State_of_Croatia.svg.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Date Of Bith: 21.02.2001
  Age: 20
  Location: Piljenice, Croatia
  <br><br>
  <b>Programing Skills:</b>
  <br>
  -Unity C#
  <br>
  -C++
  
  <br><br>
  <b>Software:</b>
  <br>
  -Fuze
  <br>
  -MakeHuman
  <br>
  -Mixamo
  <br>
  -AutoCAD
  <br>
  -ProgiCAD
  
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
